---
framework: jest
preRun:
  command:
    - npm ci         
postMerge:
  pattern: 
    - "./src/*.test.js"
  env:
    GLOAR_VARIABLE: es-ES
    ENGLISHCODE: ${{ secrets.ENGLISHCODE }}
    INTVALUE: ${{ secrets.Int_value }}
preMerge:
  pattern:
    - "./src/*.test.js"
  env:
    GLOAR_VARIABLE: es-ES
    ENGLISHCODE: ${{ secrets.ENGLISHCODE }}
    INTVALUE: ${{ secrets.Int_value }}
postRun:
  command:
    - node --version
version: 1.0.1

nodeVersion: 16.15.0
